address;source_location;insn;indent
0x12c760;/usr/local/src/conda/python-3.9.19/Python/errors.c:249;SUB	$0x18,%RSP;
0x12c764;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	%FS:0x28,%RAX;
0x12c76d;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	%RAX,0x8(%RSP);
0x12c772;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	0x28977f(%RIP),%RAX;
0x12c779;/usr/local/src/conda/python-3.9.19/Python/errors.c:254;MOV	0x58(%RAX),%RAX;
0x12c77d;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;MOV	0x8(%RSP),%RDX;
0x12c782;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;SUB	%FS:0x28,%RDX;
0x12c78b;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;JNE	12c792 <PyErr_Occurred+0x32>;
0x12c78d;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;ADD	$0x18,%RSP;
0x12c791;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;RET;
0x12c792;/usr/local/src/conda/python-3.9.19/Python/errors.c:255;CALLQ	0x251fd0(%RIP);
0x12c798;:0;NOPL	(%RAX,%RAX,1);
