address;source_location;insn;indent
0x156fd0;/usr/local/src/conda/python-3.9.19/Python/errors.c:292;SUB	$0x18,%RSP;
0x156fd4;/usr/local/src/conda/python-3.9.19/Python/errors.c:292;MOV	%FS:0x28,%RAX;
0x156fdd;/usr/local/src/conda/python-3.9.19/Python/errors.c:292;MOV	%RAX,0x8(%RSP);
0x156fe2;/usr/local/src/conda/python-3.9.19/Python/errors.c:292;XOR	%EAX,%EAX;
0x156fe4;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;MOV	0x8(%RSP),%RAX;
0x156fe9;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;SUB	%FS:0x28,%RAX;
0x156ff2;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;JNE	156ffe <_PyErr_ExceptionMatches+0x2e>;
0x156ff4;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;MOV	0x58(%RDI),%RDI;
0x156ff8;/usr/local/src/conda/python-3.9.19/Python/errors.c:294;ADD	$0x18,%RSP;
0x156ffc;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;JMP	157010 <PyErr_GivenExceptionMatches>;
0x156ffe;/usr/local/src/conda/python-3.9.19/Python/errors.c:293;CALLQ	0x227764(%RIP);
0x157004;:0;NOPW	%CS:(%RAX,%RAX,1);
0x15700f;:0;NOP;
