address;source_location;insn;indent
0x162e40;/usr/local/src/conda/python-3.9.19/Python/errors.c:224;SUB	$0x18,%RSP;
0x162e44;/usr/local/src/conda/python-3.9.19/Python/errors.c:224;MOV	%RDI,%RSI;
0x162e47;/usr/local/src/conda/python-3.9.19/Python/errors.c:224;MOV	%FS:0x28,%RAX;
0x162e50;/usr/local/src/conda/python-3.9.19/Python/errors.c:224;MOV	%RAX,0x8(%RSP);
0x162e55;/usr/local/src/conda/python-3.9.19/Python/errors.c:224;XOR	%EAX,%EAX;
0x162e57;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	0x25309a(%RIP),%RDI;
0x162e5e;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;MOV	0x8(%RSP),%RAX;
0x162e63;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;SUB	%FS:0x28,%RAX;
0x162e6c;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;JNE	162e79 <PyErr_SetNone+0x39>;
0x162e6e;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;XOR	%EDX,%EDX;
0x162e70;/usr/local/src/conda/python-3.9.19/Python/errors.c:227;ADD	$0x18,%RSP;
0x162e74;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;JMP	156a90 <_PyErr_SetObject>;
0x162e79;/usr/local/src/conda/python-3.9.19/Python/errors.c:218;CALLQ	0x21b8e9(%RIP);
0x162e7f;:0;NOP;
