address;source_location;insn;indent
0x133191;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2287;ADD	$0x10,%RBX;
0x133195;/home/sat_bot/base/conda-bld/python-split_1716596152334/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/bits/string3.h:85;XOR	%ESI,%ESI;
0x133197;:0;MOV	%R12,%RDX;
0x13319a;:0;MOV	%RBX,%RDI;
0x13319d;:0;CALLQ	0x24b6ad(%RIP);
0x1331a3;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1061;CMPQ	$0,0x28(%RBP);
0x1331a8;:0;JNE	133311 <BaseException_new+0x281>;
0x1331ae;/usr/local/src/conda/python-3.9.19/Include/cpython/objimpl.h:69;MOV	0xa8(%RBP),%RAX;
0x1331b5;/usr/local/src/conda/python-3.9.19/Include/object.h:138;MOV	%RBP,0x8(%RBX);
0x1331b9;/usr/local/src/conda/python-3.9.19/Include/cpython/objimpl.h:69;TEST	$0x2,%AH;
0x1331bc;:0;JNE	1332fb <BaseException_new+0x26b>;
0x1331c2;/usr/local/src/conda/python-3.9.19/Objects/object.c:1824;MOV	0x24c014(%RIP),%EDX;
0x1331c8;:0;TEST	%EDX,%EDX;
0x1331ca;:0;JNE	133439 <BaseException_new+0x3a9>;
0x1331d0;/usr/local/src/conda/python-3.9.19/Include/object.h:133;MOVQ	$0x1,(%RBX);
0x1331d7;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1068;TEST	$0x40,%AH;
0x1331da;:0;JE	133219 <BaseException_new+0x189>;
0x1331dc;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	0x282d15(%RIP),%RAX;
0x1331e3;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:39;LEA	-0x10(%RBX),%RCX;
0x1331e7;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:46;MOV	0x10(%RAX),%RAX;
0x1331eb;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:46;MOV	0x2c8(%RAX),%RDX;
0x1331f2;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:49;MOV	-0x8(%RBX),%RAX;
0x1331f6;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:47;MOV	0x8(%RDX),%RSI;
0x1331fa;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:49;AND	$0x3,%EAX;
0x1331fd;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:50;MOVQ	%RDX,%XMM0;
0x133202;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:49;OR	%RSI,%RAX;
0x133205;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:48;MOV	%RCX,(%RSI);
0x133208;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:50;MOVQ	%RAX,%XMM1;
0x13320d;:0;PUNPCKLQDQ	%XMM1,%XMM0;
0x133211;:0;MOVUPS	%XMM0,-0x10(%RBX);
0x133215;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_object.h:51;MOV	%RCX,0x8(%RDX);
0x133219;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:43;PXOR	%XMM0,%XMM0;
0x13321d;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:42;MOVQ	$0,0x10(%RBX);
0x133225;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:43;MOVQ	$0,0x30(%RBX);
0x13322d;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:44;MOVB	$0,0x38(%RBX);
0x133231;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:43;MOVUPS	%XMM0,0x20(%RBX);
0x133235;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:46;TEST	%R13,%R13;
0x133238;:0;JE	13334b <BaseException_new+0x2bb>;
0x13323e;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:47;MOV	%R13,0x18(%RBX);
0x133242;/usr/local/src/conda/python-3.9.19/Include/object.h:408;INCQ	(%R13);
0x133246;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:59;MOV	0x18(%RSP),%RAX;
0x13324b;:0;SUB	%FS:0x28,%RAX;
0x133254;:0;JNE	133375 <BaseException_new+0x2e5>;
0x1332fb;/usr/local/src/conda/python-3.9.19/Include/object.h:408;INCQ	(%RBP);
0x1332ff;/usr/local/src/conda/python-3.9.19/Objects/object.c:1824;CMPL	$0,0x24bed6(%RIP);
0x133306;:0;JE	1331d0 <BaseException_new+0x140>;
0x133311;/usr/local/src/conda/python-3.9.19/Include/object.h:143;XOR	%EAX,%EAX;
0x133313;/usr/local/src/conda/python-3.9.19/Include/cpython/objimpl.h:84;MOV	%RBP,%RSI;
0x133316;:0;MOV	%RBX,%RDI;
0x133319;/usr/local/src/conda/python-3.9.19/Include/object.h:143;MOV	%RAX,0x10(%RBX);
0x13331d;/usr/local/src/conda/python-3.9.19/Include/cpython/objimpl.h:84;CALL	125de0 <_PyObject_INIT.lto_priv.0>;
0x133322;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1068;TESTB	$0x40,0xa9(%RBP);
0x133329;:0;JNE	1331dc <BaseException_new+0x14c>;
0x13332f;:0;JMP	133219 <BaseException_new+0x189>;
0x13334b;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:52;CALL	12bbd0 <PyTuple_New.constprop.0>;
0x133350;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:52;MOV	%RAX,0x18(%RBX);
0x133354;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:53;TEST	%RAX,%RAX;
0x133357;:0;JNE	133246 <BaseException_new+0x1b6>;
0x133375;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:59;CALLQ	0x24b3ed(%RIP);
0x13337b;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2278;CMPL	$0,0x274(%R14);
0x133383;:0;JE	133191 <BaseException_new+0x101>;
0x133389;:0;TEST	%EDX,%EDX;
0x13338b;:0;JE	133191 <BaseException_new+0x101>;
0x133391;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2279;CMPL	$0,0x330(%R14);
0x133399;:0;JNE	133191 <BaseException_new+0x101>;
0x13339f;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2280;CMPQ	$0,0x58(%R15);
0x1333a4;:0;JNE	133191 <BaseException_new+0x101>;
0x1333aa;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1396;MOV	0x10(%R15),%RDI;
0x1333ae;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;MOV	$0x2,%ESI;
0x1333b3;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2283;MOVL	$0x1,0x330(%R14);
0x1333be;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1394;LEA	0x2c0(%RDI),%RCX;
0x1333c5;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1402;MOV	(%RCX),%EAX;  (941) 
0x1333c7;:0;CMP	%EAX,0x4(%RCX);  (941) 
0x1333ca;:0;JG	1333d9 <BaseException_new+0x349>;  (941) 
0x1333cc;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;DEC	%ESI;  (941) 
0x1333ce;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;SUB	$0x18,%RCX;  (941) 
0x1333d2;:0;CMP	$-0x1,%ESI;  (941) 
0x1333d5;:0;JNE	1333c5 <BaseException_new+0x335>;  (941) 
0x1333d7;:0;JMP	1333e6 <BaseException_new+0x356>;
0x1333d9;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1439;CMP	$0x2,%ESI;  (941) 
0x1333dc;:0;JE	1333f4 <BaseException_new+0x364>;  (941) 
0x1333de;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1442;MOV	%R15,%RDI;
0x1333e1;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1442;CALL	1e9570 <collect_with_callback>;
0x1333e6;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2285;XOR	%ECX,%ECX;
0x1333e8;:0;MOV	%ECX,0x330(%R14);
0x1333ef;:0;JMP	133191 <BaseException_new+0x101>;
0x1333f4;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1440;MOV	0x348(%RDI),%RAX;  (941) 
0x1333fb;:0;MOV	$0x4,%R8D;  (941) 
0x133401;:0;CQTO;  (941) 
0x133403;:0;IDIV	%R8;  (941) 
0x133406;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1440;CMP	%RAX,0x350(%RDI);  (941) 
0x13340d;:0;JGE	1333de <BaseException_new+0x34e>;  (941) 
0x13340f;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;SUB	$0x18,%RCX;  (941) 
0x133413;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;MOV	$0x1,%ESI;  (941) 
0x133418;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:1401;JMP	1333c5 <BaseException_new+0x335>;  (941) 
