address;source_location;insn;indent
0x5af340;/usr/local/src/conda/python-3.9.19/Python/errors.c:557;PUSH	%R15;
0x5af342;:0;PUSH	%R14;
0x5af344;:0;PUSH	%R13;
0x5af346;:0;PUSH	%R12;
0x5af348;:0;PUSH	%RBP;
0x5af349;:0;PUSH	%RBX;
0x5af34a;:0;SUB	$0x28,%RSP;
0x5af34e;/usr/local/src/conda/python-3.9.19/Python/errors.c:557;MOV	%FS:0x28,%RAX;
0x5af357;:0;MOV	%RAX,0x18(%RSP);
0x5af35c;:0;XOR	%EAX,%EAX;
0x5af35e;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	0x198bf3(%RIP),%R14;
0x5af365;/usr/local/src/conda/python-3.9.19/Python/errors.c:562;TEST	%RDI,%RDI;
0x5af368;:0;JNE	44eeec <_PyErr_ChainStackItem.cold>;
0x5af36e;/usr/local/src/conda/python-3.9.19/Python/errors.c:564;MOV	0x90(%R14),%RDI;
0x5af375;/usr/local/src/conda/python-3.9.19/Python/errors.c:568;MOV	(%RDI),%RAX;
0x5af378;/usr/local/src/conda/python-3.9.19/Python/errors.c:568;CMP	$0x73bc60,%RAX;
0x5af37e;:0;JE	5af385 <_PyErr_ChainStackItem+0x45>;
0x5af380;:0;TEST	%RAX,%RAX;
0x5af383;:0;JNE	5af3a8 <_PyErr_ChainStackItem+0x68>;
0x5af385;/usr/local/src/conda/python-3.9.19/Python/errors.c:601;MOV	0x18(%RSP),%RAX;(2716) 
0x5af38a;:0;SUB	%FS:0x28,%RAX;(2716) 
0x5af393;:0;JNE	5af43f <_PyErr_ChainStackItem+0xff>;(2716) 
0x5af399;:0;ADD	$0x28,%RSP;
0x5af39d;:0;POP	%RBX;
0x5af39e;:0;POP	%RBP;
0x5af39f;:0;POP	%R12;
0x5af3a1;:0;POP	%R13;
0x5af3a3;:0;POP	%R14;
0x5af3a5;/usr/local/src/conda/python-3.9.19/Python/errors.c:601;POP	%R15;
0x5af3a7;:0;RET;
0x5af3a8;/usr/local/src/conda/python-3.9.19/Python/errors.c:563;XOR	%R13D,%R13D;
0x5af3ab;/usr/local/src/conda/python-3.9.19/Python/errors.c:438;PXOR	%XMM0,%XMM0;
0x5af3af;/usr/local/src/conda/python-3.9.19/Python/errors.c:434;MOV	0x58(%R14),%R15;
0x5af3b3;/usr/local/src/conda/python-3.9.19/Python/errors.c:435;MOV	0x60(%R14),%RBP;
0x5af3b7;/usr/local/src/conda/python-3.9.19/Python/errors.c:587;LEA	0x10(%RSP),%RSI;
0x5af3bc;/usr/local/src/conda/python-3.9.19/Python/errors.c:438;MOVUPS	%XMM0,0x58(%R14);
0x5af3c1;/usr/local/src/conda/python-3.9.19/Python/errors.c:436;MOV	0x68(%R14),%R12;
0x5af3c5;/usr/local/src/conda/python-3.9.19/Python/errors.c:585;MOV	0x8(%RDI),%RDX;
0x5af3c9;/usr/local/src/conda/python-3.9.19/Python/errors.c:586;MOV	0x10(%RDI),%RCX;
0x5af3cd;/usr/local/src/conda/python-3.9.19/Python/errors.c:440;MOVQ	$0,0x68(%R14);
0x5af3d5;/usr/local/src/conda/python-3.9.19/Python/errors.c:587;MOV	%R14,%RDI;
0x5af3d8;/usr/local/src/conda/python-3.9.19/Python/errors.c:585;MOV	%RDX,0x8(%RSP);
0x5af3dd;/usr/local/src/conda/python-3.9.19/Python/errors.c:587;LEA	0x8(%RSP),%RDX;
0x5af3e2;/usr/local/src/conda/python-3.9.19/Python/errors.c:586;MOV	%RCX,(%RSP);
0x5af3e6;/usr/local/src/conda/python-3.9.19/Python/errors.c:587;MOV	%RSP,%RCX;
0x5af3e9;/usr/local/src/conda/python-3.9.19/Python/errors.c:584;MOV	%RAX,0x10(%RSP);
0x5af3ee;/usr/local/src/conda/python-3.9.19/Python/errors.c:587;CALL	501aa0 <_PyErr_NormalizeException>;
0x5af3f3;/usr/local/src/conda/python-3.9.19/Python/errors.c:588;MOV	(%RSP),%RSI;
0x5af3f7;/usr/local/src/conda/python-3.9.19/Python/errors.c:588;TEST	%RSI,%RSI;
0x5af3fa;:0;JE	5af406 <_PyErr_ChainStackItem+0xc6>;
0x5af3fc;/usr/local/src/conda/python-3.9.19/Python/errors.c:589;MOV	0x8(%RSP),%RDI;
0x5af401;:0;CALL	501db0 <PyException_SetTraceback>;
0x5af406;/usr/local/src/conda/python-3.9.19/Python/errors.c:593;MOV	%RBP,%RDX;
0x5af409;:0;MOV	%R15,%RSI;
0x5af40c;:0;MOV	%R14,%RDI;
0x5af40f;:0;CALL	500c10 <_PyErr_SetObject>;
0x5af414;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%R15);
0x5af417;:0;JE	44ef29 <_PyErr_ChainStackItem.cold+0x3d>;
0x5af41d;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%RBP,%RBP;
0x5af420;:0;JE	5af42c <_PyErr_ChainStackItem+0xec>;
0x5af422;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RBP);
0x5af426;:0;JE	44ef36 <_PyErr_ChainStackItem.cold+0x4a>;
0x5af42c;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%R12,%R12;
0x5af42f;:0;JNE	5af445 <_PyErr_ChainStackItem+0x105>;
0x5af431;/usr/local/src/conda/python-3.9.19/Python/errors.c:598;TEST	%R13D,%R13D;(2716) 
0x5af434;:0;JE	5af385 <_PyErr_ChainStackItem+0x45>;(2716) 
0x5af43a;:0;JMP	44ef1d <_PyErr_ChainStackItem.cold+0x31>;
0x5af43f;/usr/local/src/conda/python-3.9.19/Python/errors.c:601;CALLQ	0x161343(%RIP);(2716) 
0x5af445;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%R12);(2716) 
0x5af449;:0;JNE	5af431 <_PyErr_ChainStackItem+0xf1>;(2716) 
0x5af44b;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R12,%RDI;(2716) 
0x5af44e;:0;CALL	4d6450 <_Py_Dealloc>;(2716) 
0x5af453;:0;JMP	5af431 <_PyErr_ChainStackItem+0xf1>;(2716) 
0x5af455;/usr/local/src/conda/python-3.9.19/Include/object.h:430;NOPW	%CS:(%RAX,%RAX,1);
